### ISSUE TITLE
您好，请问代码还会继续修改吗？发现些问题

### ISSUE THREAD

**Issue by ShawWang1995** [wubinzzu/NeuRec#2]
您好，我目前试了下您提供的方法中的四个，发现有两个问题：
1、最基本的MF是可以运行的，但是运行CFGAN、NeuMF时都会有log文件不存在的问题，应该是在运行有的方法时无法自动生成log文件。
2、我还运行了IRGAN的代码。发现程序的矩阵维数设置应该有问题，错误提示如下：
`File "D:\MyProject\NeuRec-master\NeuRec-master\model\item_ranking\IRGAN.py", line 193, in get_train_data_one_user
    neg = np.random.choice(self.all_items, size=len(pos), p=prob)
  File "mtrand.pyx", line 1142, in mtrand.RandomState.choice
ValueError: a and p must have same size`
即在IRGAN.py文件的193行的 neg = np.random.choice(self.all_items, size=len(pos), p=prob)语句发生错误。
不知道您能否抽出时间查看一下，如果是我自己配置的问题希望您能指点一下，万分感谢！

**Comment by ZhongchuanSun** [comment]
@ShawWang1995  感谢您的反馈，代码还在修改中。
1. log文件名是以模型+数据集+参数+时间戳命名的，log文件不存在的原因可能是文件名太长了导致创建失败，可以试着改下/util.Logger.py的68行，缩短文件名长度，把200改为100，然后看看是否能正常运行。
2. 我们现在查看下第二个问题，解决之后再给您回复。

**Comment by ShawWang1995** [comment]
@ZhongchuanSun  好的，多谢反馈，第二个问题我是使用库中的ml-1m.train.rating数据运行的

**Comment by HeroKillerEver** [comment]
@ShawWang1995 @ZhongchuanSun IRGAN的问题是否已经解决了呢？

**Comment by sunshinelium** [comment]
@ZhongchuanSun 您好，当将数据划分方式改为‘loo'时，出现一下错误，我对这个错误没有头绪，可以请帮您帮忙看下么？
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    model.train_model()
  File "D:\project\NeuRec\model\item_ranking\MF.py", line 116, in train_model
    Evaluate.test_model(self,self.dataset)
  File "D:\project\NeuRec\evaluation\Evaluate.py", line 18, in test_model
    (hits, ndcgs,aucs) = evaluate_by_loo(model,dataset.testMatrix,dataset.testNegatives,num_thread)
  File "D:\project\NeuRec\evaluation\leaveoneout\LeaveOneOutEvaluate.py", line 28, in evaluate_by_loo
    res = list(res)
  File "D:\anaconda_1\envs\env_ncf\lib\concurrent\futures\_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "D:\anaconda_1\envs\env_ncf\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "D:\anaconda_1\envs\env_ncf\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "D:\anaconda_1\envs\env_ncf\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\project\NeuRec\evaluation\leaveoneout\LeaveOneOutEvaluate.py", line 45, in eval_by_loo_user
    target_item = _evaluateMatrix[u].indices[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
我只改动了划分方式为’loo'和模型为‘neuMF'，其余都没动，非常感谢

**Comment by jackwangsysu** [comment]
Hi, I found that it lacks the basic BPR model, will it be added later?
